id: P006633
initial_creation_type: ocr
source_metadata:
  id: bdr:W27273
  title: འཆི་མེད་མཛོད་ཀྱི་འགྲེལ་པ་འདོད་འཇོ
  author: ''
  volumes:
    fe2855a7166a4ecab59bfd4787c248d6:
      image_group_id: I1CZ974
      title: ''
      volume_number: 1
      total_pages: 426
      base_file: v001.txt
