id: IEC7F6CA6
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T11:28:22+00:00'
last_modified: '2022-06-08T05:46:59.687585+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W27273
  title: འཆི་མེད་མཛོད་ཀྱི་འགྲེལ་པ་འདོད་འཇོ
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    884B:
      image_group_id: I1CZ974
      title: ''
      total_pages: 426
      order: 1
      base_file: 884B.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
